import pokemonApi from '@/api/pokemonApi'
import { PokemonDetail } from '@/models/pokemonDetail'
import styles from '@/styles/Home.module.css'
import { GetServerSidePropsContext } from 'next'
import Head from 'next/head'

export interface ParamsPageProps {
  pokemonDetail: PokemonDetail
}

export default function PokemonDetailPage({ pokemonDetail }: ParamsPageProps) {
  console.log(pokemonDetail)

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          {pokemonDetail && (
            <>
              <p>{pokemonDetail.name}</p>
              <br />
            </>
          )}
        </div>
      </main>
    </>
  )
}

export async function getServerSideProps() {
  const data = await pokemonApi.getDetail(4)

  return {
    props: {
      pokemonDetail: data,
    },
  }
}
