import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { PokemonResponse } from '@/models/pokemonList'
import { GetServerSidePropsContext } from 'next'
import pokemonApi from '@/api/pokemonApi'
import Link from 'next/link'

export interface ParamsPageProps {
  pokemonResponse: PokemonResponse
}

export default function PokemonList({ pokemonResponse }: ParamsPageProps) {
  console.log(pokemonResponse)
  const pokemonList = pokemonResponse.results

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          {pokemonList &&
            pokemonList.length > 0 &&
            pokemonList.map((pokemon, idx) => (
              <>
                <Link href={pokemon.url} key={idx}>
                  <p>{pokemon.name}</p>
                </Link>
                <br />
              </>
            ))}
        </div>
      </main>
    </>
  )
}

export async function getServerSideProps(context: GetServerSidePropsContext) {
  const params = { limit: 20, offset: 0 }
  const data = await pokemonApi.getList(params)

  return {
    props: {
      pokemonResponse: data,
    },
  }
}
