import React, { useEffect, useState } from 'react'
import productApi from '../api/productApi'
import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { ProductsResponse } from '@/models/product'
import Image from 'next/image'

const inter = Inter({ subsets: ['latin'] })

function App() {
  const [productsResponse, setProductsResponse] = useState<ProductsResponse>()

  useEffect(() => {
    const fetchProductList = async () => {
      try {
        const params = {
          _page: 1,
          _limit: 10,
        }
        const response: ProductsResponse = await productApi.getAll(params)
        //  console.log('call api', response)

        setProductsResponse(response)
        //    productApi.getAll(params).then((response) => setProductsResponse(response))
      } catch (error) {
        console.log('Failed to fetch product list: ', error)
      }
    }

    fetchProductList()
  }, [])

  console.log('useState', productsResponse?.pagination)
  console.log('useState', productsResponse?.data)
  //setProductsResponse.map((product) => console.log(product))
  const productList = productsResponse?.data

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          <p>Try call api by axios.</p>
          {productList &&
            productList.length > 0 &&
            productList.map((product, idx) => (
              <div key={idx}>
                <p>{product.name}</p>
                <p>{product.salePrice}</p>
                <Image src={product.images[0]} alt={product.name} width={150} height={150} />
                <p>{product.name}</p>
              </div>
            ))}
        </div>
      </main>
    </>
  )
}

export default App
